name: protoc_builder
description: A build script for compiling Protocol Buffers without needing to manually install protoc or the protoc_plugin.
version: 0.5.0
repository: https://github.com/pikaju/dart-protoc-builder

environment:
  sdk: ">=2.16.0 <4.0.0"

dependencies:
  archive: ^4.0.9
  build: ">=2.5.0 <=4.1.0"
  http: ">=0.13.4 <2.0.0"
  path: ^1.9.1
  yaml: ^3.1.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
